<script setup>
    // toggle
</script>

<template>
    <div class="View centered">
        <h1>Effets</h1>
        <div class="effets">
            <button class="subtleOvershoot" @click="(e) => e.target.classList.toggle(`scale`)">Subtle Overshoot on transform <br><br> Click me</button>
            <div class="card holoShimmer">
                <div class="shimmer"></div>
                Subtle gradient + Holographic shimmer <br><br> Generated by Claude.ai
            </div>
        </div>
    </div>
</template>

<style scoped>
    .effets {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
    }
    button {
        width: fit-content;
        min-height: 50px;
    }

    .card {
        position: relative;
        width: 200px;
        /* width: fit-content; */
        height: 200px;
        border-radius: 12px;
        padding: 20px;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .subtleOvershoot {
        /* Effet subtle Overshoot from claude.ai */
        transition: transform .2s cubic-bezier(.34, 1.56, .64, 1);

        &.scale {
            transform: scale(1.5);
        }
    }

    
    .holoShimmer {
        position: relative;
        background: linear-gradient(160deg, #1e1520 0%, #110d10 60%, #0d090c 100%);

        .shimmer {
            position: absolute;
            inset: 0;
            border-radius: 8px;
            background: linear-gradient(125deg,
                    transparent 40%,
                    rgba(255, 255, 255, 0.04) 50%,
                    transparent 60%);
            background-size: 200% 200%;
            animation: shimmer 3s ease infinite;
            pointer-events: none;
            z-index: 10;
        }
    }

    @keyframes shimmer {
        0% {
            background-position: 200% 0%;
        }

        100% {
            background-position: -200% 0%;
        }
    }
</style>